@startuml
!theme crt-green

note top of GreetingService
 Aggregation implies a relationship where the child can exist
 independently of the parent. Example: Class (parent) and Student (child).
 Delete the Class and the Students still exist.
 GreetingService can exist separate from WeatherGreeting.
end note

class WeatherGreeting {
    + TransmitGreeting(location:string, time:DateTime?) : string
}

class GreetingService {
+ TransmitGreeting(greeting: string)
}

class WeatherService {
+ FetchWeatherData(mapPoint: MapPoint, dateTime: DateTime):WeatherData
}

class LocationService {
+ GetLocation(location: string): MapPoint
}

WeatherGreeting o---> GreetingService
WeatherGreeting o---> WeatherService
WeatherGreeting o---> LocationService
@enduml
